[package]
name = "rust-hex-viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
crossterm = "0.27.0"
ratatui = "0.28.1"
eframe = "0.27.2"
